//
// Created by Henning Tandberg on 10/05/2025.
//

#ifndef USB_RUBBER_DUCKY_COMMANDPARSERTESTS_H
#define USB_RUBBER_DUCKY_COMMANDPARSERTESTS_H

void KeyboardKeypressCommand_ParseKeyboardKeypress_CommandTypeIsSetToKeyboardKeypress(void);
void KeyboardKeypressCommand_ParseKeyboardKeypress_CommandLenIsAmountOfKeyboardKeypress(void);
void KeyboardKeypressCommand_ParseKeyboardKeypress_CommandContainsAllKeyboardKeypress(void);

void KeyboardKeypressCommandWithAllModifiers_ParseKeyboardKeypress_CommandContainsAllModifiers(void);
void KeyboardKeypressCommandWithAllSpecials_ParseKeyboardKeypress_CommandContainsAllSpecials(void);
void KeyboardKeypressCommandWithAllNavigation_ParseKeyboardKeypress_CommandContainsAllNavigation(void);
void KeyboardKeypressCommandWithAllNumeric_ParseKeyboardKeypress_CommandContainsAllNumeric(void);
void KeyboardKeypressCommandWithAllFunctionAndEscape_ParseKeyboardKeypress_CommandContainsAllFunctionAndEscape(void);
void KeyboardKeypressCommandWithAllFunctionControl_ParseKeyboardKeypress_CommandContainsAllFunctionControl(void);

void KeyboardKeypressCommandWithAllNumbers_ParseKeyboardKeypress_CommandContainsAllNumbers(void);
void KeyboardKeypressCommandWithAllCapitalLetters_ParseKeyboardKeypress_CommandContainsAllCapitalLetters(void);
void KeyboardKeypressCommandWithAllLetters_ParseKeyboardKeypress_CommandContainsAllLetters(void);

#endif //USB_RUBBER_DUCKY_COMMANDPARSERTESTS_H
