name: Build, Test and Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./code

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Test
        run: |
          pio test -e test

      - name: Build Atmega Code
        run: pio run -e leonardo

      - name: Build Atmega Pass Through Code
        run: pio run -e leonardo-pass-through

      - name: Build ESP Code
        run: pio run -e esp12e

      - name: Build ESP File System
        run: pio run -e esp12e -t buildfs

      - name: Tar and strip the binary
        run: |
          mkdir tmp
          mv .pio/build/leonardo/firmware.hex tmp/atmega32u4.hex
          mv .pio/build/leonardo-pass-through/firmware.hex tmp/atmega32u4-pass-through.hex
          mv .pio/build/esp12e/firmware.bin tmp/esp8266.bin
          mv .pio/build/esp12e/littlefs.bin tmp/esp8266-fs.bin
          tar -cavf build.tar.gz tmp/*

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build.tar.gz